### ISSUE TITLE
dump in sg analysis

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#187]
On a auto-generated input by clVer
Branch: 178_ApiInputClver
input: clVerExamples\inputClver4.json

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x61d322]

goroutine 1 [running]:
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).getProtocolTcpudpRule(0x8?, 0xc00061a460)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:133 +0xc2
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).getSGRule(0xc00000b948?, {0x7aef60?, 0xc00061a460?})
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:196 +0x55
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).getSGrules(0x67b440?, 0xc00060c0e0)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:211 +0xf2
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).prepareAnalyzer(0xc00062f180, 0xc00046e180?, 0xc00048ff60?)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:281 +0x5e
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.getSGconfig(0xc00062dc80, 0xc000098180, 0xc00001f2c0?)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/parser.go:584 +0x5e5
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.NewCloudConfig(0xc00062dc80)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/parser.go:702 +0x595
main._main({0xc000036090?, 0x60?, 0x0?})
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/cmd/analyzer/main.go:57 +0x10d
main.main()
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/cmd/analyzer/main.go:85 +0x52
exit status 2

```

**Comment by ShiriMoran** [comment]
The relevant code still dumps on the same input, in what seems to be a similar but not identical fail @adisos @zivnevo 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x87cdde]

goroutine 1 [running]:
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).getProtocolTcpudpRule(0x8?, 0xc000445040)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:133 +0xbe
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).getSGRule(0xc0000a5040?, {0xa0ee20?, 0xc000445040?})
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:191 +0x55
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/parser.go:584 +0x5e5
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.NewCloudConfig(0xc000635c80)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/parser.go:702 +0x595
main._main({0xc000036090?, 0x60?, 0x0?})
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/cmd/analyzer/main.go:57 +0x10d
main.main()
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/cmd/analyzer/main.go:85 +0x52
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).getSGrules(0x12bb440?, 0xc0002376c0)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:206 +0xf2
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*SGAnalyzer).prepareAnalyzer(0xc000240cb0, 0xc00069a9f0?, 0xc0000254e0?)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/sg_analysis.go:276 +0x5e
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.getSGconfig(0xc000709c80, 0xc00011c200, 0xc00001eac0?)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/parser.go:584 +0x5e5
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.NewCloudConfig(0xc000709c80)
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/pkg/ibmvpc/parser.go:702 +0x595
main._main({0xc0000d4010?, 0x60?, 0x0?})
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/cmd/analyzer/main.go:57 +0x10d
main.main()
        C:/Users/SHIRIMORAN/npguard_realy_new/vpc-network-config-analyzer/cmd/analyzer/main.go:85 +0x52
exit status 2
```

**Comment by adisos** [comment]
After merging `main` to branch `178_ApiInputClver` , could not reproduce the dump

**Comment by ShiriMoran** [comment]
> After merging `main` to branch `178_ApiInputClver` , could not reproduce the dump

my mistake - seems I forget to update to the latest git prior to 'merge origin/main'
