### ISSUE TITLE
add test example + fix issue for its analysis 

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#217]
example `sg_testing_3` crashed on main branch with `all_endpoints` analysis type

```
$ ./bin/vpcanalyzer -vpc-config pkg/ibmvpc/examples/input_sg_testing_3.json
load_balancers resource type is not yet supported
routing_tables resource type is not yet supported
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x3fa7fd]

goroutine 1 [running]:
github.com/np-guard/vpc-network-config-analyzer/pkg/common.(*ConnectionSet).Union(0xc0000702a0?, 0x804d18?)
        vpc-network-config-analyzer/pkg/common/connectionset.go:167 +0x1d
github.com/np-guard/vpc-network-config-analyzer/pkg/ibmvpc.(*NaclLayer).AllowedConnectivity(0xc000070480, {0x804d18, 0xc00013d880}, {0x804f58, 0xc000117740}, 0x28?)
       vpc-network-config-analyzer/pkg/ibmvpc/vpc.go:271 +0xd4
github.com/np-guard/vpc-network-config-analyzer/pkg/vpcmodel.
...

```

**Comment by adisos** [comment]
The issue was a bug in computation of external disjoint ip-blocks.
