### ISSUE TITLE
Crash when running diff_all_endpoints

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-analyzer#584]
Running with the following parameter causes a crash:
```
./bin/vpcanalyzer -analysis-type diff_all_endpoints -quiet -vpc-config pkg/ibmvpc/examples/input/input_sg_testing_default.json -vpc-config-second pkg/ibmvpc/examples/input/input_sg_testing_3.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa48bba]

goroutine 1 [running]:
github.com/np-guard/vpc-network-config-analyzer/pkg/vpcmodel.(*VPCConfig).GetVPCNetworkConnectivity(0x0, 0x0, 0x0)
        /home/nevo/vpc-network-config-analyzer/pkg/vpcmodel/nodesConnectivity.go:31 +0xba
github.com/np-guard/vpc-network-config-analyzer/pkg/vpcmodel.(*VPCConfig).getAllowedConnectionsCombined(0x7fc6e6878108?, 0x30?)
        /home/nevo/vpc-network-config-analyzer/pkg/vpcmodel/semanticDiff.go:127 +0x26
github.com/np-guard/vpc-network-config-analyzer/pkg/vpcmodel.configsForDiff.GetDiff({0xc0000c2580?, 0x0?, 0xc00029e220?})
        /home/nevo/vpc-network-config-analyzer/pkg/vpcmodel/semanticDiff.go:81 +0x65
github.com/np-guard/vpc-network-config-analyzer/pkg/vpcmodel.NewOutputGenerator(0xc000594240, 0x0, 0x5, 0xf?, 0x0, 0x1)
        /home/nevo/vpc-network-config-analyzer/pkg/vpcmodel/output.go:116 +0x537
main.analysisVPCConfigs(0xc000594240?, 0xc000162b60?, {0x0, 0x0})
        /home/nevo/vpc-network-config-analyzer/cmd/analyzer/main.go:84 +0x425
main._main({0xc000034090?, 0x60?, 0x0?})
        /home/nevo/vpc-network-config-analyzer/cmd/analyzer/main.go:244 +0x2c5
main.main()
        /home/nevo/vpc-network-config-analyzer/cmd/analyzer/main.go:254 +0x49
```

**Comment by zivnevo** [comment]
No crash if running with `-analysis-type all_endpoints` and providing each of the configs separately.

**Comment by zivnevo** [comment]
The command line to run, after the change to the CLI:
```shell
./bin/vpcanalyzer diff endpoints --quiet --vpc-config pkg/ibmvpc/examples/input/input_sg_testing_default.json --vpc-config-second pkg/ibmvpc/examples/input/input_sg_testing_3.json
```

**Comment by ShiriMoran** [comment]
The problem seems to be related to @haim-kermany  https://github.com/np-guard/vpc-network-config-analyzer/pull/572
Specifically, there is a nil in the struct's 2nd config. 
I've opened a branch `584_diff_endpoints_crash` in which I return an error when this situation is detected:
```
go run .\cmd\analyzer diff endpoints -q -c pkg/ibmvpc/examples/input/input_sg_testing_3.json --vpc-config-second pkg/ibmvpc/examples/input/input_sg_testing1_new_2SGs.json      
2024/05/21 13:29:02 npGuard error: diff endpoints config to compare is nil; nohting in cConfigs.ConfigToCompare(crn:17). exiting...
```

**Comment by haim-kermany** [comment]
the crash happened we try to compare two configs with different uid
the this bug was here before my PR, see diff:
https://github.com/np-guard/vpc-network-config-analyzer/pull/572/files#diff-2d30567843e3b956cc646d06611dfb66e5bcfba28f7c83a78abdf978226405cd

**Comment by haim-kermany** [comment]
@zivnevo @adisos do we want to allow diff of two configs with different uid? Error? Warning?

**Comment by ShiriMoran** [comment]
1. Indeed, seems that thus far I compared a `cfg` to its modified copy - thus with the same `id`.  Still, I'm pretty sure that when I wrote the diff such a restriction did not exist. It was inserted later as part of the modification of the `vpcConfig` struct, and somehow we missed it
2. I consider **name**

**Comment by haim-kermany** [comment]
yes, VPC uid
